name: silverpine
favicon: null
layout_spectrum: 0.5567225266713649
typography_spectrum: 0.8289900759700686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#471612'
    - '#dba397'
    - '#9d5032'
    - '#b5684a'
    - '#8c767b'
  brandStrength: 0.6534057583194226
  lightness: 0.9688805446494371
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
